        !COMPILER-GENERATED INTERFACE MODULE: Tue Mar 27 23:54:12 2018
        MODULE READIN__genmod
          INTERFACE 
            SUBROUTINE READIN(MANUAL)
              LOGICAL(KIND=4) :: MANUAL
            END SUBROUTINE READIN
          END INTERFACE 
        END MODULE READIN__genmod
