.SILENT:

VMFILES = mafft.tcl pkgIndex.tcl
VMVERSION = 1.1
DIR = $(PLUGINDIR)/noarch/tcl/mafft$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying mafft $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

