      CHARACTER*80 FUNCTION GETNAM(NAMEIN)
C
C    THIS FUNCTION IS DESIGNED FOR USE ON A VMS AND ON A UNIX
C    SYSTEM.  IF YOUR SYSTEM IS VMS, COMMENT OUT THE LINE
C    "      CALL GETENV(NAMEIN, NAMOUT)", FURTHER ON IN THIS FUNCTION.
C    IF YOUR SYSTEM IS UNIX, MAKE SURE THE LINE IS NOT
C    COMMENTED OUT.
C    ON A UNIX SYSTEM, GETENV WILL CONSULT THE ENVIRONMENT
C    FOR THE CURRENT ALIAS OF THE CHARACTER STRING CONTAINED IN
C    'NAMEIN'.  THE ALIAS, IF IT EXISTS, OR THE ORIGINAL NAME IN NAMEIN
C    WILL BE RETURNED.
C
      CHARACTER*(*) NAMEIN
      CHARACTER*(80) NAMOUT
      NAMOUT=' '
      CALL GETENV(NAMEIN, NAMOUT)
      IF (NAMOUT.EQ.'  ') NAMOUT=NAMEIN
      GETNAM = NAMOUT
      RETURN
      END
