      SUBROUTINE UPCASE(KEYWRD)
      CHARACTER*80 KEYWRD
      CHARACTER*80 KEYBUF
      ICAPA=ICHAR('A')
      ILOWA=ICHAR('a')
      ILOWZ=ICHAR('z')
      KEYBUF=KEYWRD
      DO 10 I=1,80
         ILINE=ICHAR(KEYWRD(I:I))
         IF(ILINE.GE.ILOWA.AND.ILINE.LE.ILOWZ) THEN
            KEYWRD(I:I)=CHAR(ILINE+ICAPA-ILOWA)
         ENDIF
   10 CONTINUE
      RETURN
      END
